// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../taengson/agent-chat-desktop/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "agentic-evaluation:event": main$0.AgenticEvaluationEvent;
            "chat:event": main$0.ChatEvent;
        }
    }
}
