// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApproveBenchmarkSyncV2Pairing(requestID: string): $CancellablePromise<$models.BenchmarkSyncV2State> {
    return $Call.ByID(3250957274, requestID);
}

export function CancelChat(requestID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2522773405, requestID);
}

export function CheckBenchmarkSyncV2Pairing(requestID: string): $CancellablePromise<$models.BenchmarkSyncV2OutgoingPairing> {
    return $Call.ByID(4186873435, requestID);
}

export function ClearBenchmarkSyncV2Logs(): $CancellablePromise<$models.BenchmarkSyncV2State> {
    return $Call.ByID(3957585205);
}

/**
 * ConfigureBenchmarkSyncV2DirectTLS configures and starts the application's
 * own v2 HTTPS listener. The private-key contents remain in the selected PEM
 * file and are never returned to the frontend or written to app state.
 */
export function ConfigureBenchmarkSyncV2DirectTLS(publicHTTPSURL: string, certificatePath: string, privateKeyPath: string, listenAddress: string): $CancellablePromise<$models.BenchmarkSyncV2State> {
    return $Call.ByID(3279866869, publicHTTPSURL, certificatePath, privateKeyPath, listenAddress);
}

export function ConfirmBenchmarkSyncV2Pairing(requestID: string): $CancellablePromise<$models.BenchmarkSyncV2State> {
    return $Call.ByID(441034003, requestID);
}

/**
 * CreateBenchmarkSyncV2PairingInvitation returns a short-lived invitation
 * secret exactly once. The secret is never written to the sync state or logs.
 */
export function CreateBenchmarkSyncV2PairingInvitation(): $CancellablePromise<$models.BenchmarkSyncV2Invitation> {
    return $Call.ByID(1691730614);
}

export function CreateConversation(): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(1021935206);
}

export function CreateModelBenchmark(benchmark: $models.ModelBenchmark): $CancellablePromise<$models.ModelBenchmark> {
    return $Call.ByID(1784962657, benchmark);
}

export function DeleteConversation(id: string): $CancellablePromise<void> {
    return $Call.ByID(1702807921, id);
}

export function DeleteModelBenchmark(id: string): $CancellablePromise<void> {
    return $Call.ByID(2912364830, id);
}

export function DeleteSavedConnectionProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(4225912054, id);
}

/**
 * GenerateBenchmarkSyncV2TLSCertificateRequest makes a new TLS private key
 * and certificate signing request in user-selected files. It does not issue a
 * trusted certificate; the CSR must be signed by a public or organisation CA.
 */
export function GenerateBenchmarkSyncV2TLSCertificateRequest(publicHTTPSURL: string, privateKeyPath: string, certificateRequestPath: string): $CancellablePromise<$models.BenchmarkSyncV2TLSCertificateRequest> {
    return $Call.ByID(1483035123, publicHTTPSURL, privateKeyPath, certificateRequestPath);
}

/**
 * GetBenchmarkSyncV2Identity creates the local v2 identity on first use and
 * returns only its public information. Pairing uses these fingerprints to help
 * a user spot a different or replaced device key.
 */
export function GetBenchmarkSyncV2Identity(): $CancellablePromise<$models.BenchmarkSyncV2Identity> {
    return $Call.ByID(3451725207);
}

export function GetBenchmarkSyncV2State(): $CancellablePromise<$models.BenchmarkSyncV2State> {
    return $Call.ByID(439277450);
}

/**
 * ImportBenchmarkReport adds new results embedded in an exported Markdown or
 * HTML benchmark report to the local benchmark history.
 */
export function ImportBenchmarkReport(path: string): $CancellablePromise<$models.ModelBenchmarkImportResult> {
    return $Call.ByID(1730891493, path);
}

export function ListConversations(): $CancellablePromise<$models.ConversationSummary[] | null> {
    return $Call.ByID(1664713955);
}

export function ListModelBenchmarks(): $CancellablePromise<$models.ModelBenchmarkSummary[] | null> {
    return $Call.ByID(86776914);
}

export function ListModels(profile: $models.ConnectionProfile): $CancellablePromise<$models.Model[] | null> {
    return $Call.ByID(919729239, profile);
}

export function ListSavedConnectionProfiles(): $CancellablePromise<$models.SavedConnectionProfile[] | null> {
    return $Call.ByID(2816371074);
}

export function LoadConnectionProfile(): $CancellablePromise<$models.SavedConnectionProfile> {
    return $Call.ByID(1786048502);
}

export function OpenConversation(id: string): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(3465756378, id);
}

export function OpenModelBenchmark(id: string): $CancellablePromise<$models.ModelBenchmark> {
    return $Call.ByID(2364498477, id);
}

/**
 * PrepareModelBenchmarkForSecureSync adds a durable v2 proof to an already
 * completed local result. The forthcoming v2 transport calls this before it
 * creates an encrypted outbound record batch.
 */
export function PrepareModelBenchmarkForSecureSync(id: string): $CancellablePromise<$models.ModelBenchmark> {
    return $Call.ByID(1622920301, id);
}

export function RejectBenchmarkSyncV2Pairing(requestID: string): $CancellablePromise<$models.BenchmarkSyncV2State> {
    return $Call.ByID(3791427230, requestID);
}

/**
 * SaveBenchmarkExport writes a user-selected benchmark report.
 */
export function SaveBenchmarkExport(path: string, contents: string): $CancellablePromise<void> {
    return $Call.ByID(760497389, path, contents);
}

/**
 * SaveChatShare writes a user-selected chat response share file.
 */
export function SaveChatShare(path: string, contents: string): $CancellablePromise<void> {
    return $Call.ByID(1701743309, path, contents);
}

export function SaveConnectionProfile(profile: $models.SavedConnectionProfile): $CancellablePromise<$models.SavedConnectionProfile> {
    return $Call.ByID(3622685069, profile);
}

export function SaveConversation(conversation: $models.Conversation): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(3192203735, conversation);
}

export function SaveModelBenchmark(benchmark: $models.ModelBenchmark): $CancellablePromise<$models.ModelBenchmark> {
    return $Call.ByID(3578344020, benchmark);
}

export function SaveNamedConnectionProfile(profile: $models.SavedConnectionProfile): $CancellablePromise<$models.SavedConnectionProfile> {
    return $Call.ByID(3901251290, profile);
}

export function StartBenchmarkSyncV2Pairing(publicHTTPSURL: string, pairingSecret: string): $CancellablePromise<$models.BenchmarkSyncV2OutgoingPairing> {
    return $Call.ByID(1663538243, publicHTTPSURL, pairingSecret);
}

export function StartChat(request: $models.ChatRequest): $CancellablePromise<void> {
    return $Call.ByID(1745474569, request);
}

export function StopBenchmarkSyncV2Endpoint(): $CancellablePromise<$models.BenchmarkSyncV2State> {
    return $Call.ByID(3266274070);
}

export function UpdateBenchmarkSyncV2DeviceName(name: string): $CancellablePromise<$models.BenchmarkSyncV2State> {
    return $Call.ByID(2609947213, name);
}
