// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ApproveBenchmarkSyncPairing(requestID: string): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(1241619706, requestID);
}

export function CancelAgenticEvaluation(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1665828458, id);
}

export function CancelChat(requestID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2522773405, requestID);
}

export function CheckBenchmarkSyncPairing(requestID: string): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(3387929511, requestID);
}

export function ClearBenchmarkSyncLogs(): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(458136437);
}

export function CreateBenchmarkSyncPairingCode(): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(2196712624);
}

export function CreateConversation(): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(1021935206);
}

export function CreateModelBenchmark(benchmark: $models.ModelBenchmark): $CancellablePromise<$models.ModelBenchmark> {
    return $Call.ByID(1784962657, benchmark);
}

export function DeleteAgenticEvaluation(id: string): $CancellablePromise<void> {
    return $Call.ByID(1206529825, id);
}

export function DeleteBenchmarkSyncPeer(deviceID: string): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(3461360998, deviceID);
}

export function DeleteConversation(id: string): $CancellablePromise<void> {
    return $Call.ByID(1702807921, id);
}

export function DeleteModelBenchmark(id: string): $CancellablePromise<void> {
    return $Call.ByID(2912364830, id);
}

export function DeleteSavedConnectionProfile(id: string): $CancellablePromise<void> {
    return $Call.ByID(4225912054, id);
}

export function GetBenchmarkSyncState(): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(2636766830);
}

/**
 * ImportBenchmarkReport adds new results embedded in an exported Markdown or
 * HTML benchmark report to the local benchmark history.
 */
export function ImportBenchmarkReport(path: string): $CancellablePromise<$models.ModelBenchmarkImportResult> {
    return $Call.ByID(1730891493, path);
}

export function ListAgenticEvaluationScenarios(): $CancellablePromise<$models.AgenticEvaluationScenarioSummary[] | null> {
    return $Call.ByID(396275063);
}

export function ListAgenticEvaluations(): $CancellablePromise<$models.AgenticEvaluationSummary[] | null> {
    return $Call.ByID(3594639805);
}

export function ListConversations(): $CancellablePromise<$models.ConversationSummary[] | null> {
    return $Call.ByID(1664713955);
}

export function ListModelBenchmarks(): $CancellablePromise<$models.ModelBenchmarkSummary[] | null> {
    return $Call.ByID(86776914);
}

export function ListModels(profile: $models.ConnectionProfile): $CancellablePromise<$models.Model[] | null> {
    return $Call.ByID(919729239, profile);
}

export function ListSavedConnectionProfiles(): $CancellablePromise<$models.SavedConnectionProfile[] | null> {
    return $Call.ByID(2816371074);
}

export function LoadConnectionProfile(): $CancellablePromise<$models.SavedConnectionProfile> {
    return $Call.ByID(1786048502);
}

export function OpenAgenticEvaluation(id: string): $CancellablePromise<$models.AgenticEvaluation> {
    return $Call.ByID(531987124, id);
}

export function OpenConversation(id: string): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(3465756378, id);
}

export function OpenModelBenchmark(id: string): $CancellablePromise<$models.ModelBenchmark> {
    return $Call.ByID(2364498477, id);
}

export function RejectBenchmarkSyncPairing(requestID: string): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(2463881622, requestID);
}

export function RunBenchmarkSync(deviceID: string, direction: string): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(356619878, deviceID, direction);
}

/**
 * SaveBenchmarkExport writes a user-selected benchmark report.
 */
export function SaveBenchmarkExport(path: string, contents: string): $CancellablePromise<void> {
    return $Call.ByID(760497389, path, contents);
}

/**
 * SaveChatShare writes a user-selected chat response share file.
 */
export function SaveChatShare(path: string, contents: string): $CancellablePromise<void> {
    return $Call.ByID(1701743309, path, contents);
}

export function SaveConnectionProfile(profile: $models.SavedConnectionProfile): $CancellablePromise<$models.SavedConnectionProfile> {
    return $Call.ByID(3622685069, profile);
}

export function SaveConversation(conversation: $models.Conversation): $CancellablePromise<$models.Conversation> {
    return $Call.ByID(3192203735, conversation);
}

export function SaveModelBenchmark(benchmark: $models.ModelBenchmark): $CancellablePromise<$models.ModelBenchmark> {
    return $Call.ByID(3578344020, benchmark);
}

export function SaveNamedConnectionProfile(profile: $models.SavedConnectionProfile): $CancellablePromise<$models.SavedConnectionProfile> {
    return $Call.ByID(3901251290, profile);
}

export function StartAgenticEvaluation(request: $models.AgenticEvaluationStartRequest): $CancellablePromise<$models.AgenticEvaluation> {
    return $Call.ByID(2806942, request);
}

export function StartBenchmarkSyncPairing(address: string, code: string): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(4201909007, address, code);
}

export function StartChat(request: $models.ChatRequest): $CancellablePromise<void> {
    return $Call.ByID(1745474569, request);
}

export function UpdateBenchmarkSyncDeviceName(name: string): $CancellablePromise<$models.BenchmarkSyncState> {
    return $Call.ByID(2030519413, name);
}
