// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BenchmarkSyncV2Identity contains only public identity information. The
 * corresponding private keys are kept in the operating system's secret store
 * and are never returned to the frontend or written to the app data folder.
 */
export interface BenchmarkSyncV2Identity {
    "version": number;
    "createdAt": string;
    "signingKeyID": string;
    "signingFingerprint": string;
    "keyAgreementKeyID": string;
    "keyAgreementFingerprint": string;
}

/**
 * BenchmarkSyncV2Invitation is returned only when a user creates an
 * invitation. PairingSecret is never copied into state, audit logs, or JSON.
 */
export interface BenchmarkSyncV2Invitation {
    "publicHTTPSURL": string;
    "pairingSecret": string;
    "expiresAt": string;
    "host": BenchmarkSyncV2Identity;
}

/**
 * BenchmarkSyncV2Log is a local audit record. It deliberately stores neither
 * pairing secrets, private keys, plaintext benchmark payloads, nor ciphertext.
 */
export interface BenchmarkSyncV2Log {
    "id": string;
    "occurredAt": string;
    "event": string;
    "status": string;
    "message"?: string;
}

/**
 * BenchmarkSyncV2OutgoingPairing omits the invitation secret deliberately.
 * The secret exists only in process memory until pairing is resolved.
 */
export interface BenchmarkSyncV2OutgoingPairing {
    "requestID": string;
    "host": BenchmarkSyncV2Peer;
    "status": string;
    "expiresAt": string;
}

/**
 * BenchmarkSyncV2Peer is public trust information for a paired device. Its
 * E2EE session secrets stay in the OS secret store once encryption is enabled.
 */
export interface BenchmarkSyncV2Peer {
    "deviceName": string;
    "publicHTTPSURL"?: string;
    "signingKeyID": string;
    "signingPublicKeyPEM": string;
    "signingFingerprint": string;
    "keyAgreementKeyID": string;
    "keyAgreementPublicKeyPEM": string;
    "keyAgreementFingerprint": string;
    "trustedAt": string;
}

/**
 * BenchmarkSyncV2PendingPairing is a host-side request awaiting a fingerprint
 * comparison and explicit user approval.
 */
export interface BenchmarkSyncV2PendingPairing {
    "requestID": string;
    "requester": BenchmarkSyncV2Peer;
    "expiresAt": string;
}

/**
 * BenchmarkSyncV2RecordProof travels with a completed benchmark. It contains
 * no private key and lets a trusted peer, or an imported report with its
 * public key, detect modifications to the signed benchmark fields.
 */
export interface BenchmarkSyncV2RecordProof {
    "version": number;
    "type": string;
    "keyID": string;
    "originBenchmarkID": string;
    "signedAt": string;
    "payloadSHA256": string;
    "signingPublicKeyPEM": string;
    "signature": string;
}

/**
 * BenchmarkSyncV2State is the complete public state for the replacement sync
 * feature. Unlike v1, it has no LAN addresses, one-time display code, or
 * bearer-token-derived peer state.
 */
export interface BenchmarkSyncV2State {
    "deviceName": string;
    "identity": BenchmarkSyncV2Identity;
    "publicHTTPSURL"?: string;
    "tlsCertificatePath"?: string;
    "tlsPrivateKeyPath"?: string;
    "listenAddress"?: string;
    "endpointStatus": string;
    "peers": BenchmarkSyncV2Peer[] | null;
    "pendingPairings": BenchmarkSyncV2PendingPairing[] | null;
    "outgoingPairings": BenchmarkSyncV2OutgoingPairing[] | null;
    "logs": BenchmarkSyncV2Log[] | null;
}

/**
 * ChatAttachment stores the locally extracted and selected text for an
 * attached text, source-code file, text-based PDF, DOCX, or XLSX file. The
 * original file is never copied from its location.
 */
export interface ChatAttachment {
    "name": string;
    "size": number;
    "content": string;
    "truncated"?: boolean;
    "selectionSummary"?: string;
}

export interface ChatEvent {
    "requestID": string;
    "type": string;
    "delta"?: string;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
    "error"?: string;
}

export interface ChatMessage {
    "role": string;
    "content": string;
}

export interface ChatRequest {
    "requestID": string;
    "profile": ConnectionProfile;
    "model": string;
    "messages": ChatMessage[] | null;
    "reasoningEffort"?: string;
    "benchmark": boolean;
}

export interface ConnectionProfile {
    "baseURL": string;
    "apiKey": string;
}

export interface Conversation {
    "id": string;
    "title": string;
    "createdAt": string;
    "updatedAt": string;
    "messages": ConversationMessage[] | null;
}

export interface ConversationMessage {
    "id": string;
    "role": string;
    "content": string;
    "status": string;
    "model"?: string;
    "attachments"?: ChatAttachment[] | null;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
}

export interface ConversationSummary {
    "id": string;
    "title": string;
    "updatedAt": string;
    "messageCount": number;
}

export interface Model {
    "id": string;
    "ownedBy"?: string;
}

export interface ModelBenchmark {
    "id": string;
    "imported": boolean;

    /**
     * Source keeps the record's local provenance. Imported is retained for
     * compatibility with reports created by older versions of the app.
     */
    "source"?: string;
    "originDeviceID"?: string;
    "originDeviceName"?: string;
    "originBenchmarkID"?: string;
    "profileID": string;
    "profileName": string;
    "profileBaseURL": string;
    "model": string;
    "reasoningEffort"?: string;
    "suiteName": string;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
    "cases": ModelBenchmarkCase[] | null;
    "proof"?: BenchmarkSyncV2RecordProof | null;
}

export interface ModelBenchmarkCase {
    "id": string;
    "category": string;
    "title": string;
    "prompt": string;
    "content": string;
    "status": string;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
    "error"?: string;
}

/**
 * ModelBenchmarkImportResult describes the records added from a report and
 * how many matching records were already in the local history.
 */
export interface ModelBenchmarkImportResult {
    "imported": ModelBenchmark[] | null;
    "duplicateCount": number;
}

export interface ModelBenchmarkSummary {
    "id": string;
    "imported": boolean;
    "source": string;
    "originDeviceName"?: string;
    "suiteName": string;
    "model": string;
    "reasoningEffort"?: string;
    "profileName": string;
    "profileBaseURL": string;
    "status": string;
    "updatedAt": string;
    "caseCount": number;
    "completedCaseCount": number;
    "averageTotalDurationMs": number;
    "averageFirstTokenDurationMs": number;
    "averageGenerationSpeed": number;
}

/**
 * ResponseMetrics is measured locally for each streaming response. The first
 * token duration is zero when a server finishes without emitting text.
 */
export interface ResponseMetrics {
    "totalDurationMs": number;
    "firstTokenDurationMs": number;
}

/**
 * SavedConnectionProfile deliberately excludes the API key and model. The API
 * key exists only in memory, and models are fetched again when a user connects.
 */
export interface SavedConnectionProfile {
    "id": string;
    "name": string;
    "baseURL": string;
}

/**
 * TokenUsage is the token accounting reported by a compatible chat server for
 * one completed request. Prompt and completion tokens are kept separately so
 * the frontend can present total token usage without estimating tokens from
 * text.
 */
export interface TokenUsage {
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
}
