// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AgenticEvaluation {
    "id": string;
    "profileID": string;
    "profileName": string;
    "profileBaseURL": string;
    "modelIDs": string[] | null;
    "scenarioIDs": string[] | null;
    "repetitions": number;
    "reasoningEffort"?: string;
    "executionRules": AgenticExecutionRules;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
    "runs": AgenticEvaluationRun[] | null;
}

export interface AgenticEvaluationAction {
    "step": number;
    "type": string;
    "toolName"?: string;
    "arguments"?: string;
    "output"?: string;
    "status": string;
    "rawContent"?: string;
    "occurredAt": string;
}

export interface AgenticEvaluationChange {
    "resource": string;
    "before"?: string;
    "after"?: string;
}

export interface AgenticEvaluationEvent {
    "evaluationID": string;
    "runID"?: string;
    "type": string;
    "status"?: string;
    "run"?: AgenticEvaluationRun | null;
    "error"?: string;
}

export interface AgenticEvaluationResult {
    "passed": boolean;
    "outcome": string;
    "summary": string;
    "requirements"?: string[] | null;
    "violations"?: string[] | null;
}

export interface AgenticEvaluationRun {
    "id": string;
    "model": string;
    "scenarioID": string;
    "scenarioVersion": string;
    "initialStateHash"?: string;
    "graderVersion": string;
    "environment": string;
    "category": string;
    "title": string;
    "goal": string;
    "variant": number;
    "status": string;
    "startedAt"?: string;
    "finishedAt"?: string;
    "actions": AgenticEvaluationAction[] | null;
    "stateChanges"?: AgenticEvaluationChange[] | null;
    "result"?: AgenticEvaluationResult | null;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
    "error"?: string;
}

export interface AgenticEvaluationScenarioSummary {
    "id": string;
    "version": string;
    "environment": string;
    "category": string;
    "title": string;
    "description": string;
}

/**
 * AgenticEvaluationStartRequest starts one sequential queue. Profile.APIKey is
 * used only while the queue is running and is deliberately excluded from the
 * saved AgenticEvaluation record.
 */
export interface AgenticEvaluationStartRequest {
    "profile": ConnectionProfile;
    "profileID": string;
    "profileName": string;
    "modelIDs": string[] | null;
    "scenarioIDs": string[] | null;
    "repetitions": number;
    "reasoningEffort"?: string;
}

export interface AgenticEvaluationSummary {
    "id": string;
    "profileName": string;
    "profileBaseURL": string;
    "models": string[] | null;
    "scenarioCount": number;
    "repetitions": number;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
    "runCount": number;
    "finishedRunCount": number;
    "passedRunCount": number;
}

/**
 * AgenticExecutionRules records the shared evaluation contract. It makes a
 * stored result interpretable even after defaults evolve in a later release.
 */
export interface AgenticExecutionRules {
    "actionFormatVersion": string;
    "systemPromptVersion": string;
    "toolDefinitionVersion": string;
    "graderVersion": string;
    "maxActions": number;
    "maxInvalidActions": number;
    "contextLimitBytes": number;
    "responseLimitBytes": number;
    "toolOutputLimitBytes": number;
    "runTimeoutSeconds": number;
    "actionTimeoutSeconds": number;
}

export interface BenchmarkSyncLog {
    "id": string;
    "occurredAt": string;
    "peerDeviceID"?: string;
    "peerDeviceName"?: string;
    "direction": string;
    "status": string;
    "sentCount": number;
    "receivedCount": number;
    "duplicateCount": number;
    "ignoredCount": number;
    "conflictCount": number;
    "message"?: string;
}

export interface BenchmarkSyncPairRequest {
    "requestID": string;
    "deviceID": string;
    "deviceName": string;
    "address": string;
    "createdAt": string;
    "status": string;
}

/**
 * BenchmarkSyncPeer is a trusted device. Its secret tokens are kept separately
 * in the local settings file and are never returned to the frontend.
 */
export interface BenchmarkSyncPeer {
    "deviceID": string;
    "deviceName": string;
    "address": string;
    "connectedAt": string;
}

export interface BenchmarkSyncState {
    "deviceID": string;
    "deviceName": string;
    "localAddresses": string[] | null;
    "pairingCode"?: string;
    "pairingExpiresAt"?: string;
    "peers": BenchmarkSyncPeer[] | null;
    "incomingRequests": BenchmarkSyncPairRequest[] | null;
    "outgoingRequests": BenchmarkSyncPairRequest[] | null;
    "logs": BenchmarkSyncLog[] | null;
}

/**
 * ChatAttachment stores the locally extracted and selected text for an
 * attached text, source-code file, text-based PDF, DOCX, or XLSX file. The
 * original file is never copied from its location.
 */
export interface ChatAttachment {
    "name": string;
    "size": number;
    "content": string;
    "truncated"?: boolean;
    "selectionSummary"?: string;
}

export interface ChatEvent {
    "requestID": string;
    "type": string;
    "delta"?: string;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
    "error"?: string;
}

export interface ChatMessage {
    "role": string;
    "content": string;
}

export interface ChatRequest {
    "requestID": string;
    "profile": ConnectionProfile;
    "model": string;
    "messages": ChatMessage[] | null;
    "reasoningEffort"?: string;
    "benchmark": boolean;
}

export interface ConnectionProfile {
    "baseURL": string;
    "apiKey": string;
}

export interface Conversation {
    "id": string;
    "title": string;
    "createdAt": string;
    "updatedAt": string;
    "messages": ConversationMessage[] | null;
}

export interface ConversationMessage {
    "id": string;
    "role": string;
    "content": string;
    "status": string;
    "model"?: string;
    "attachments"?: ChatAttachment[] | null;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
}

export interface ConversationSummary {
    "id": string;
    "title": string;
    "updatedAt": string;
    "messageCount": number;
}

export interface Model {
    "id": string;
    "ownedBy"?: string;
}

export interface ModelBenchmark {
    "id": string;
    "imported": boolean;

    /**
     * Source keeps the record's local provenance. Imported is retained for
     * compatibility with reports created by older versions of the app.
     */
    "source"?: string;
    "originDeviceID"?: string;
    "originDeviceName"?: string;
    "originBenchmarkID"?: string;
    "profileID": string;
    "profileName": string;
    "profileBaseURL": string;
    "model": string;
    "reasoningEffort"?: string;
    "suiteName": string;
    "status": string;
    "createdAt": string;
    "updatedAt": string;
    "cases": ModelBenchmarkCase[] | null;
}

export interface ModelBenchmarkCase {
    "id": string;
    "category": string;
    "title": string;
    "prompt": string;
    "content": string;
    "status": string;
    "usage"?: TokenUsage | null;
    "metrics"?: ResponseMetrics | null;
    "error"?: string;
}

/**
 * ModelBenchmarkImportResult describes the records added from a report and
 * how many matching records were already in the local history.
 */
export interface ModelBenchmarkImportResult {
    "imported": ModelBenchmark[] | null;
    "duplicateCount": number;
}

export interface ModelBenchmarkSummary {
    "id": string;
    "imported": boolean;
    "source": string;
    "originDeviceName"?: string;
    "suiteName": string;
    "model": string;
    "reasoningEffort"?: string;
    "profileName": string;
    "profileBaseURL": string;
    "status": string;
    "updatedAt": string;
    "caseCount": number;
    "completedCaseCount": number;
    "averageTotalDurationMs": number;
    "averageFirstTokenDurationMs": number;
    "averageGenerationSpeed": number;
}

/**
 * ResponseMetrics is measured locally for each streaming response. The first
 * token duration is zero when a server finishes without emitting text.
 */
export interface ResponseMetrics {
    "totalDurationMs": number;
    "firstTokenDurationMs": number;
}

/**
 * SavedConnectionProfile deliberately excludes the API key and model. The API
 * key exists only in memory, and models are fetched again when a user connects.
 */
export interface SavedConnectionProfile {
    "id": string;
    "name": string;
    "baseURL": string;
}

/**
 * TokenUsage is the token accounting reported by a compatible chat server for
 * one completed request. Prompt and completion tokens are kept separately so
 * the frontend can present total token usage without estimating tokens from
 * text.
 */
export interface TokenUsage {
    "promptTokens": number;
    "completionTokens": number;
    "totalTokens": number;
}
